CREATE DATABASE shop;
USE shop;
 
CREATE TABLE products(
 id INT(250) AUTO_INCREMENT PRIMARY KEY NOT NULL,
 title VARCHAR (250) NOT NULL,
 price DECIMAL NOT NULL,
 brandname  VARCHAR (250) NOT NULL,
 image VARCHAR (250) NOT NULL,
 description LONGTEXT
 featured VARCHAR (250) NOT NULL
);